development:
  adapter: mysql2
  database: bedrock
  host: localhost
  username: root
  password: 
  # socket: /tmp/mysql.sock
production:
  adapter: mysql2
  database: bedrock_foundations_production
  pool: 15
  host: localhost
  username: root 
  password: 
